version: '3.7'
services:
  arango:
    image: arangodb
    environment:
    - ARANGO_NO_AUTH=1
    ports:
      - 8529:8529
    volumes:
      - ./database/arangodb3:/var/lib/arangodb3
      - ./database/arangodb3-apps:/var/lib/arangodb3-apps